name: Build GUI

on:
  push:
    paths:
      - .github/workflows/build-gui.yml
      - gui/**
      - package*.json
  pull_request:
    paths:
      - .github/workflows/build-gui.yml
      - gui/**
      - package*.json
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    env:
      # Don't mark warnings as errors
      CI: false

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - if: matrix.os == 'ubuntu-latest'
        name: Set up Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Build
        run: |
          npm ci
          npm run tauri build

      - if: matrix.os == 'windows-latest'
        name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: SlimeVR-GUI
          # A file, directory or wildcard pattern that describes what to upload
          path: target/release/slimevr.exe

      - if: matrix.os == 'ubuntu-latest'
        name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: SlimeVR-GUI-Deb
          # A file, directory or wildcard pattern that describes what to upload
          path: target/release/bundle/deb/slimevr*.deb

      - if: matrix.os == 'ubuntu-latest'
        name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: SlimeVR-GUI-AppImage
          # A file, directory or wildcard pattern that describes what to upload
          path: target/release/bundle/appimage/slimevr*.AppImage
